var ElementosQuimicos = {

    "SIGLAS": ["H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Uut", "Fl", "Uup", "Lv", "Uus", "Uuo", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr"],

    "ELEMENTOS": {
        "H": {
            "nome": "Hidrogênio",
            "sigla": "H",
            "nox": [1, -1],
            "eletrons": [1, 0, 0, 0, 0, 0, 0],
            "numeroAtomico": 1,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "1s1",
            "cor": [255, 255, 255],
            "grupo": "Hidrogênio"
        },
        "He": {
            "nome": "Hélio",
            "sigla": "He",
            "nox": [0, 0, 0, 0, 0, 0, 0],
            "eletrons": [2],
            "numeroAtomico": 2,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "1s2",
            "cor": [217, 255, 255],
            "grupo": "Gases Nobres"
        },
        "Li": {
            "nome": "Lítio",
            "sigla": "Li",
            "nox": [1, 0, -1],
            "eletrons": [2, 1, 0, 0, 0, 0, 0],
            "numeroAtomico": 3,
            "eletronegatividade": 1,
            "configuracaoEletronica": "1s2 2s1",
            "cor": [204, 128, 255],
            "grupo": "Metais Alcalinos"
        },
        "Be": {
            "nome": "Berílio",
            "sigla": "Be",
            "nox": [2],
            "eletrons": [2, 2, 0, 0, 0, 0, 0],
            "numeroAtomico": 4,
            "eletronegatividade": 1.5,
            "configuracaoEletronica": "1s2 2s2",
            "cor": [194, 255, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "B": {
            "nome": "Boro",
            "sigla": "B",
            "nox": [3],
            "eletrons": [2, 3, 0, 0, 0, 0, 0],
            "numeroAtomico": 5,
            "eletronegatividade": 2.0,
            "configuracaoEletronica": "1s2 2s2 2p1",
            "cor": [255, 181, 181],
            "grupo": "Não Metais"
        },
        "C": {
            "nome": "Carbono",
            "sigla": "C",
            "nox": [-4, 4, -2, 2],
            "eletrons": [2, 4, 0, 0, 0, 0, 0],
            "numeroAtomico": 6,
            "eletronegatividade": 2.5,
            "configuracaoEletronica": "1s2 2s2 2p2",
            "cor": [144, 144, 144],
            "grupo": "Não Metais"
        },
        "N": {
            "nome": "Nitrogênio",
            "sigla": "N",
            "nox": [-3, +3, 1, -1, 2, 3, 4, 5],
            "eletrons": [2, 5, 0, 0, 0, 0, 0],
            "numeroAtomico": 7,
            "eletronegatividade": 3.0,
            "configuracaoEletronica": "1s2 2s2 2p3",
            "cor": [48, 80, 248],
            "grupo": "Não Metais"
        },
        "O": {
            "nome": "Oxigênio",
            "sigla": "O",
            "nox": [-2, 2],
            "eletrons": [2, 6, 0, 0, 0, 0, 0],
            "numeroAtomico": 8,
            "eletronegatividade": 3.44,
            "configuracaoEletronica": "1s2 2s2 2p4",
            "cor": [255, 13, 13],
            "grupo": "Não Metais"
        },
        "F": {
            "nome": "Flúor",
            "sigla": "F",
            "nox": [-1],
            "eletrons": [2, 7, 0, 0, 0, 0, 0],
            "numeroAtomico": 9,
            "eletronegatividade": 4.0,
            "configuracaoEletronica": "1s2 2s2 2p5",
            "cor": [144, 224, 80],
            "grupo": "Não Metais"
        },
        "Ne": {
            "nome": "Neônio",
            "sigla": "Ne",
            "nox": [0],
            "eletrons": [2, 8, 0, 0, 0, 0, 0],
            "numeroAtomico": 10,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "1s2 2s2 2p6",
            "cor": [179, 227, 245],
            "grupo": "Gases Nobres"
        },
        "Na": {
            "nome": "Sódio",
            "sigla": "Na",
            "nox": [1],
            "eletrons": [2, 8, 1, 0, 0, 0, 0, 0],
            "numeroAtomico": 11,
            "eletronegatividade": 0.9,
            "configuracaoEletronica": "3s1",
            "cor": [171, 92, 242],
            "grupo": "Metais Alcalinos"
        },
        "Mg": {
            "nome": "Magnésio",
            "sigla": "Mg",
            "nox": [2],
            "eletrons": [2, 8, 2, 0, 0, 0, 0],
            "numeroAtomico": 12,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "3s2",
            "cor": [138, 255, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "Al": {
            "nome": "Alumínio",
            "sigla": "Al",
            "nox": [3],
            "eletrons": [2, 8, 3, 0, 0, 0, 0],
            "numeroAtomico": 13,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "3s2 3p1",
            "cor": [191, 166, 166],
            "grupo": "Outros Metais"
        },
        "Si": {
            "nome": "Silício",
            "sigla": "Si",
            "nox": [4, 2, -4],
            "eletrons": [2, 8, 4, 0, 0, 0, 0],
            "numeroAtomico": 14,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "3s2 3p2",
            "cor": [240, 200, 160],
            "grupo": "Não Metais"
        },
        "P": {
            "nome": "Fósforo",
            "sigla": "P",
            "nox": [3, -2, -3, 1, 2, 4],
            "eletrons": [2, 8, 5, 0, 0, 0, 0],
            "numeroAtomico": 15,
            "eletronegatividade": 2.1,
            "configuracaoEletronica": "3s2 3p3",
            "cor": [255, 128, 0],
            "grupo": "Não Metais"
        },
        "S": {
            "nome": "Enxofre",
            "sigla": "S",
            "nox": [6, 2, 0, -1, 1, 2, 3, 4, 5],
            "eletrons": [2, 8, 6, 0, 0, 0, 0],
            "numeroAtomico": 16,
            "eletronegatividade": 2.5,
            "configuracaoEletronica": "3s2 3p4",
            "cor": [255, 255, 48],
            "grupo": "Não Metais"
        },
        "Cl": {
            "nome": "Cloro",
            "sigla": "Cl",
            "nox": [-1, 1, 3, 4, 5, 6, 7],
            "eletrons": [2, 8, 7, 0, 0, 0, 0],
            "numeroAtomico": 17,
            "eletronegatividade": 3.1,
            "configuracaoEletronica": "3s2 3p5",
            "cor": [31, 240, 31],
            "grupo": "Não Metais"
        },
        "Ar": {
            "nome": "Argônio",
            "sigla": "Ar",
            "nox": [0],
            "eletrons": [2, 8, 8, 0, 0, 0, 0],
            "numeroAtomico": 18,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "3s2 3p6",
            "cor": [128, 209, 227],
            "grupo": "Gases Nobres"
        },
        "K": {
            "nome": "Potássio",
            "sigla": "K",
            "nox": [1],
            "eletrons": [2, 8, 8, 1, 0, 0, 0],
            "numeroAtomico": 19,
            "eletronegatividade": 0.8,
            "configuracaoEletronica": "4s1",
            "cor": [143, 64, 212],
            "grupo": "Metais Alcalinos"
        },
        "Ca": {
            "nome": "Cálcio",
            "sigla": "Ca",
            "nox": [2],
            "eletrons": [2, 8, 8, 2, 0, 0, 0],
            "numeroAtomico": 20,
            "eletronegatividade": 1.0,
            "configuracaoEletronica": "4s2",
            "cor": [61, 255, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "Sc": {
            "nome": "Escândio",
            "sigla": "Sc",
            "nox": [3, 2],
            "eletrons": [2, 8, 9, 2, 0, 0, 0],
            "numeroAtomico": 21,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "4s2 3d1",
            "cor": [230, 230, 230],
            "grupo": "Metais de Transição"
        },
        "Ti": {
            "nome": "Titânio",
            "sigla": "Ti",
            "nox": [4, 2, 3],
            "eletrons": [2, 8, 10, 2, 0, 0, 0],
            "numeroAtomico": 22,
            "eletronegatividade": 1.5,
            "configuracaoEletronica": "4s2 3d2",
            "cor": [191, 194, 199],
            "grupo": "Metais de Transição"
        },
        "V": {
            "nome": "Vanádio",
            "sigla": "V",
            "nox": [5, 4, 3, 2],
            "eletrons": [2, 8, 11, 2, 0, 0, 0],
            "numeroAtomico": 23,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "4s2 3d3",
            "cor": [166, 166, 171],
            "grupo": "Metais de Transição"
        },
        "Cr": {
            "nome": "Crômio",
            "sigla": "Cr",
            "nox": [3, -2, 2, -1, 6],
            "eletrons": [2, 8, 13, 1, 0, 0, 0],
            "numeroAtomico": 24,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "4s1 3d5",
            "cor": [138, 153, 199],
            "grupo": "Metais de Transição"
        },
        "Mn": {
            "nome": "Manganês",
            "sigla": "Mn",
            "nox": [2, -3, 1, 4, -1, 5, 6, 3, -2, 7],
            "eletrons": [2, 8, 13, 2, 0, 0, 0],
            "numeroAtomico": 25,
            "eletronegatividade": 1.55,
            "configuracaoEletronica": "4s2 3d5",
            "cor": [156, 122, 199],
            "grupo": "Metais de Transição"
        },
        "Fe": {
            "nome": "Ferro",
            "sigla": "Fe",
            "nox": [3, 2, 1, -2, -1, 4, 5, 6],
            "eletrons": [2, 8, 14, 2, 0, 0, 0],
            "numeroAtomico": 26,
            "eletronegatividade": 1.8,
            "configuracaoEletronica": "4s2 3d6",
            "cor": [224, 102, 51],
            "grupo": "Metais de Transição"
        },
        "Co": {
            "nome": "Cobalto",
            "sigla": "Co",
            "nox": [2, -1, 5, 3, 4],
            "eletrons": [2, 8, 15, 2, 0, 0, 0],
            "numeroAtomico": 27,
            "eletronegatividade": 1.8,
            "configuracaoEletronica": "4s2 3d7",
            "cor": [240, 144, 160],
            "grupo": "Metais de Transição"
        },
        "Ni": {
            "nome": "Níquel",
            "sigla": "Ni",
            "nox": [2, -1, 1, 3, 4],
            "eletrons": [2, 8, 16, 2, 0, 0, 0],
            "numeroAtomico": 28,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4s2 3d8",
            "cor": [80, 208, 80],
            "grupo": "Metais de Transição"
        },
        "Cu": {
            "nome": "Cobre",
            "sigla": "Cu",
            "nox": [2, 1, 3, 4],
            "eletrons": [2, 8, 18, 1, 0, 0, 0],
            "numeroAtomico": 29,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4s1 3d10",
            "cor": [200, 128, 51],
            "grupo": "Metais de Transição"
        },
        "Zn": {
            "nome": "Zinco",
            "sigla": "Zn",
            "nox": [2],
            "eletrons": [2, 8, 18, 2, 0, 0, 0],
            "numeroAtomico": 30,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "4s2 3d10",
            "cor": [125, 128, 176],
            "grupo": "Metais de Transição"
        },
        "Ga": {
            "nome": "Gálio",
            "sigla": "Ga",
            "nox": [3, 1],
            "eletrons": [2, 8, 18, 3, 0, 0, 0],
            "numeroAtomico": 31,
            "eletronegatividade": 1.8,
            "configuracaoEletronica": "4s2 3d10 4p1",
            "cor": [194, 143, 143],
            "grupo": "Outros Metais"
        },
        "Ge": {
            "nome": "Germânio",
            "sigla": "Ge",
            "nox": [4, 2, -4],
            "eletrons": [2, 8, 18, 4, 0, 0, 0],
            "numeroAtomico": 32,
            "eletronegatividade": 2.01,
            "configuracaoEletronica": "3d10 4s2 4p2",
            "cor": [102, 143, 143],
            "grupo": "Outros Metais"
        },
        "As": {
            "nome": "Arsênico",
            "sigla": "As",
            "nox": [3, -3, 5],
            "eletrons": [2, 8, 18, 5, 0, 0, 0],
            "numeroAtomico": 33,
            "eletronegatividade": 2.1,
            "configuracaoEletronica": "3d10 4s2 4p3",
            "cor": [189, 128, 227],
            "grupo": "Não Metais"
        },
        "Se": {
            "nome": "Selênio",
            "sigla": "Se",
            "nox": [4, -2, 6],
            "eletrons": [2, 8, 18, 6, 0, 0, 0],
            "numeroAtomico": 34,
            "eletronegatividade": 2.5,
            "configuracaoEletronica": "3d10 4s2 4p4",
            "cor": [255, 161, 0],
            "grupo": "Não Metais"
        },
        "Br": {
            "nome": "Bromo",
            "sigla": "Br",
            "nox": [-1, 1, 3, 5, 7],
            "eletrons": [2, 8, 18, 7, 0, 0, 0],
            "numeroAtomico": 35,
            "eletronegatividade": 2.9,
            "configuracaoEletronica": "3d10 4s2 4p5",
            "cor": [166, 41, 41],
            "grupo": "Não Metais"
        },
        "Kr": {
            "nome": "Criptônio",
            "sigla": "Kr",
            "nox": [2],
            "eletrons": [2, 8, 18, 8, 0, 0, 0],
            "numeroAtomico": 36,
            "eletronegatividade": 3.0,
            "configuracaoEletronica": "3d10 4s2 4p6",
            "cor": [92, 184, 209],
            "grupo": "Gases Nobres"
        },
        "Rb": {
            "nome": "Rubídio",
            "sigla": "Rb",
            "nox": [1],
            "eletrons": [2, 8, 18, 8, 1, 0, 0],
            "numeroAtomico": 37,
            "eletronegatividade": 0.8,
            "configuracaoEletronica": "5s1",
            "cor": [112, 46, 176],
            "grupo": "Metais Alcalinos"
        },
        "Sr": {
            "nome": "Estrôncio",
            "sigla": "Sr",
            "nox": [2],
            "eletrons": [2, 8, 18, 8, 2, 0, 0],
            "numeroAtomico": 38,
            "eletronegatividade": 1.0,
            "configuracaoEletronica": "5s2",
            "cor": [0, 255, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "Y": {
            "nome": "Ítrio",
            "sigla": "Y",
            "nox": [3],
            "eletrons": [2, 8, 18, 9, 2, 0, 0],
            "numeroAtomico": 39,
            "eletronegatividade": 1.22,
            "configuracaoEletronica": "4d1 5s2",
            "cor": [148, 255, 255],
            "grupo": "Metais de Transição"
        },
        "Zr": {
            "nome": "Zircônio",
            "sigla": "Zr",
            "nox": [4, 2],
            "eletrons": [2, 8, 18, 10, 2, 0, 0],
            "numeroAtomico": 40,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "4d2 5s2",
            "cor": [148, 224, 224],
            "grupo": "Metais de Transição"
        },
        "Nb": {
            "nome": "Nióbio",
            "sigla": "Nb",
            "nox": [5, 3, 2],
            "eletrons": [2, 8, 18, 12, 1, 0, 0],
            "numeroAtomico": 41,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "4d4 5s1",
            "cor": [115, 194, 201],
            "grupo": "Metais de Transição"
        },
        "Mo": {
            "nome": "Molibdênio",
            "sigla": "Mo",
            "nox": [6, 5, 4, 3, 2],
            "eletrons": [2, 8, 18, 13, 1, 0, 0],
            "numeroAtomico": 42,
            "eletronegatividade": 2.1,
            "configuracaoEletronica": "4d5 5s1",
            "cor": [84, 181, 181],
            "grupo": "Metais de Transição"
        },
        "Tc": {
            "nome": "Tecnécio",
            "sigla": "Tc",
            "nox": [7, 3, 1, 5, 6],
            "eletrons": [2, 8, 18, 13, 2, 0, 0],
            "numeroAtomico": 43,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4d5 5s2",
            "cor": [59, 158, 158],
            "grupo": "Metais de Transição"
        },
        "Ru": {
            "nome": "Rutênio",
            "sigla": "Ru",
            "nox": [3, 2, -2, 4, 5, 6, 7, 8],
            "eletrons": [2, 8, 18, 15, 1],
            "numeroAtomico": 44,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4d7 5s1",
            "cor": [36, 143, 143],
            "grupo": "Metais de Transição"
        },
        "Rh": {
            "nome": "Ródio",
            "sigla": "Rh",
            "nox": [1, 3, 4, 5, 6],
            "eletrons": [2, 8, 18, 16, 1, 0, 0],
            "numeroAtomico": 45,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4d8 5s1",
            "cor": [10, 125, 140],
            "grupo": "Metais de Transição"
        },
        "Pd": {
            "nome": "Paládio",
            "sigla": "Pd",
            "nox": [2, 4],
            "eletrons": [2, 8, 18, 18, 0, 0, 0],
            "numeroAtomico": 46,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4d10",
            "cor": [0, 105, 133],
            "grupo": "Metais de Transição"
        },
        "Ag": {
            "nome": "Prata",
            "sigla": "Ag",
            "nox": [1, 2, 3],
            "eletrons": [2, 8, 18, 18, 1, 0, 0],
            "numeroAtomico": 47,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4d10 5s1",
            "cor": [192, 192, 192],
            "grupo": "Metais de Transição"
        },
        "Cd": {
            "nome": "Cádmio",
            "sigla": "Cd",
            "nox": [2],
            "eletrons": [2, 8, 18, 18, 2, 0, 0],
            "numeroAtomico": 48,
            "eletronegatividade": 1.7,
            "configuracaoEletronica": "4d10 5s2",
            "cor": [255, 217, 143],
            "grupo": "Metais de Transição"
        },
        "In": {
            "nome": "Índio",
            "sigla": "In",
            "nox": [3, 1],
            "eletrons": [2, 8, 18, 18, 3, 0, 0],
            "numeroAtomico": 49,
            "eletronegatividade": 1.78,
            "configuracaoEletronica": "4d10 5s2 5p1",
            "cor": [166, 117, 115],
            "grupo": "Outros Metais"
        },
        "Sn": {
            "nome": "Estanho",
            "sigla": "Sn",
            "nox": [4, 2],
            "eletrons": [2, 8, 18, 18, 4, 0, 0],
            "numeroAtomico": 50,
            "eletronegatividade": 1.96,
            "configuracaoEletronica": "4d10 5s2 5p2",
            "cor": [102, 128, 128],
            "grupo": "Outros Metais"
        },
        "Sb": {
            "nome": "Antimônio",
            "sigla": "Sb",
            "nox": [3, -3, 5],
            "eletrons": [2, 8, 18, 18, 5, 0, 0],
            "numeroAtomico": 51,
            "eletronegatividade": 2.05,
            "configuracaoEletronica": "4d10 5s2 5p3",
            "cor": [158, 99, 181],
            "grupo": "Outros Metais"
        },
        "Te": {
            "nome": "Telúrio",
            "sigla": "Te",
            "nox": [4, -2, 5, 6],
            "eletrons": [2, 8, 18, 18, 6, 0, 0],
            "numeroAtomico": 52,
            "eletronegatividade": 2.1,
            "configuracaoEletronica": "4d10 5s2 5p4",
            "cor": [212, 122, 0],
            "grupo": "Não Metais"
        },
        "I": {
            "nome": "Iodo",
            "sigla": "I",
            "nox": [-1, 1, 5, 7],
            "eletrons": [2, 8, 18, 18, 7, 0, 0],
            "numeroAtomico": 53,
            "eletronegatividade": 2.66,
            "configuracaoEletronica": "4d10 5s2 5p5",
            "cor": [148, 0, 148],
            "grupo": "Não Metais"
        },
        "Xe": {
            "nome": "Xenônio",
            "sigla": "Xe",
            "nox": [4, 2, 0, 6, 8],
            "eletrons": [2, 8, 18, 18, 8, 0, 0],
            "numeroAtomico": 54,
            "eletronegatividade": 2.6,
            "configuracaoEletronica": "4d10 5s2 5p6",
            "cor": [66, 158, 176],
            "grupo": "Gases Nobres"
        },
        "Cs": {
            "nome": "Césio",
            "sigla": "Cs",
            "nox": [1],
            "eletrons": [2, 8, 18, 18, 8, 1, 0],
            "numeroAtomico": 55,
            "eletronegatividade": 0.79,
            "configuracaoEletronica": "6s1",
            "cor": [87, 23, 143],
            "grupo": "Metais Alcalinos"
        },
        "Ba": {
            "nome": "Bário",
            "sigla": "Ba",
            "nox": [2],
            "eletrons": [2, 8, 18, 18, 8, 2, 0],
            "numeroAtomico": 56,
            "eletronegatividade": 0.89,
            "configuracaoEletronica": "6s2",
            "cor": [0, 201, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "Lu": {
            "nome": "Lutécio",
            "sigla": "Lu",
            "nox": [3],
            "eletrons": [2, 8, 18, 32, 9, 2, 0],
            "numeroAtomico": 71,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "4f14 5d1 6s2",
            "cor": [0, 171, 36],
            "grupo": "Metais de Transição"
        },
        "Hf": {
            "nome": "Háfnio",
            "sigla": "Hf",
            "nox": [4, 3],
            "eletrons": [2, 8, 18, 32, 10, 2, 0],
            "numeroAtomico": 72,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "4f14 5d2 6s2",
            "cor": [77, 194, 255],
            "grupo": "Metais de Transição"
        },
        "Ta": {
            "nome": "Tântalo",
            "sigla": "Ta",
            "nox": [5, 4, 1, 3],
            "eletrons": [2, 8, 18, 32, 11, 2, 0],
            "numeroAtomico": 73,
            "eletronegatividade": 1.5,
            "configuracaoEletronica": "4f14 5d3 6s2",
            "cor": [77, 166, 255],
            "grupo": "Metais de Transição"
        },
        "W": {
            "nome": "Tungstênio",
            "sigla": "W",
            "nox": [6, 5, 4, 2],
            "eletrons": [2, 8, 18, 32, 12, 2, 0],
            "numeroAtomico": 74,
            "eletronegatividade": 2.4,
            "configuracaoEletronica": "4f14 5d4 6s2",
            "cor": [33, 148, 214],
            "grupo": "Metais de Transição"
        },
        "Re": {
            "nome": "Rênio",
            "sigla": "Re",
            "nox": [7, 1, 2, 3, 4, 5, 6],
            "eletrons": [2, 8, 18, 32, 13, 2, 0],
            "numeroAtomico": 75,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4f14 5d5 6s2",
            "cor": [38, 125, 171],
            "grupo": "Metais de Transição"
        },
        "Os": {
            "nome": "Ósmio",
            "sigla": "Os",
            "nox": [4, 2, -1, 3, 5, 6, 7, 8],
            "eletrons": [2, 8, 18, 32, 14, 2, 0],
            "numeroAtomico": 76,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4f14 5d6 6s2",
            "cor": [38, 102, 150],
            "grupo": "Metais de Transição"
        },
        "Ir": {
            "nome": "Irídio",
            "sigla": "Ir",
            "nox": [1, 4, 2, 3, 5, 6],
            "eletrons": [2, 8, 18, 32, 15, 2, 0],
            "numeroAtomico": 77,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4f14 5d7 6s2",
            "cor": [23, 84, 135],
            "grupo": "Metais de Transição"
        },
        "Pt": {
            "nome": "Platina",
            "sigla": "Pt",
            "nox": [2, 4, 5, 6],
            "eletrons": [2, 8, 18, 32, 17, 1, 0],
            "numeroAtomico": 78,
            "eletronegatividade": 2.28,
            "configuracaoEletronica": "4f14 5d9 6s1",
            "cor": [208, 208, 224],
            "grupo": "Metais de Transição"
        },
        "Au": {
            "nome": "Ouro",
            "sigla": "Au",
            "nox": [3, 1, 2, -1, 7, 5],
            "eletrons": [2, 8, 18, 32, 18, 1, 0],
            "numeroAtomico": 79,
            "eletronegatividade": 2.54,
            "configuracaoEletronica": "4f14 5d10 6s1",
            "cor": [255, 209, 35],
            "grupo": "Metais de Transição"
        },
        "Hg": {
            "nome": "Mercúrio",
            "sigla": "Hg",
            "nox": [2, 1],
            "eletrons": [2, 8, 18, 32, 18, 2, 0],
            "numeroAtomico": 80,
            "eletronegatividade": 1.9,
            "configuracaoEletronica": "4f14 5d10 6s2",
            "cor": [184, 184, 208],
            "grupo": "Metais de Transição"
        },
        "Tl": {
            "nome": "Tálio",
            "sigla": "Tl",
            "nox": [3, 1],
            "eletrons": [2, 8, 18, 32, 18, 3, 0],
            "numeroAtomico": 81,
            "eletronegatividade": 1.6,
            "configuracaoEletronica": "4f14 5d10 6s2 6p1",
            "cor": [166, 84, 77],
            "grupo": "Outros Metais"
        },
        "Pb": {
            "nome": "Chumbo",
            "sigla": "Pb",
            "nox": [2, 4],
            "eletrons": [2, 8, 18, 32, 18, 4, 0],
            "numeroAtomico": 82,
            "eletronegatividade": 2.30,
            "configuracaoEletronica": "4f14 5d10 6s2 6p2",
            "cor": [87, 89, 97],
            "grupo": "Outros Metais"
        },
        "Bi": {
            "nome": "Bismuto",
            "sigla": "Bi",
            "nox": [3, 5],
            "eletrons": [2, 8, 18, 32, 18, 5, 0],
            "numeroAtomico": 83,
            "eletronegatividade": 2.0,
            "configuracaoEletronica": "4f14 5d10 6s2 6p3",
            "cor": [158, 79, 181],
            "grupo": "Outros Metais"
        },
        "Po": {
            "nome": "Polônio",
            "sigla": "Po",
            "nox": [4, 2, -2, 6],
            "eletrons": [2, 8, 18, 32, 18, 6, 0],
            "numeroAtomico": 84,
            "eletronegatividade": 2.0,
            "configuracaoEletronica": "4f14 5d10 6s2 6p4",
            "cor": [171, 92, 0],
            "grupo": "Outros Metais"
        },
        "At": {
            "nome": "Astato",
            "sigla": "At",
            "nox": [-1, 1, 3, 5, 7],
            "eletrons": [2, 8, 18, 32, 18, 7, 0],
            "numeroAtomico": 85,
            "eletronegatividade": 2.2,
            "configuracaoEletronica": "4f14 5d10 6s2 6p5",
            "cor": [117, 79, 69],
            "grupo": "Não Metais"
        },
        "Rn": {
            "nome": "Radônio",
            "sigla": "Rn",
            "nox": [2],
            "eletrons": [2, 8, 18, 32, 18, 8, 0],
            "numeroAtomico": 86,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "4f14 5d10 6s2 6p6",
            "cor": [66, 130, 150],
            "grupo": "Gases Nobres"
        },
        "Fr": {
            "nome": "Frâncio",
            "sigla": "Fr",
            "nox": [1],
            "eletrons": [2, 8, 18, 32, 18, 8, 1],
            "numeroAtomico": 87,
            "eletronegatividade": 0.7,
            "configuracaoEletronica": "7s1",
            "cor": [66, 0, 102],
            "grupo": "Metais Alcalinos"
        },
        "Ra": {
            "nome": "Rádio",
            "sigla": "Ra",
            "nox": [2],
            "eletrons": [2, 8, 18, 32, 18, 8, 2],
            "numeroAtomico": 88,
            "eletronegatividade": 0.89,
            "configuracaoEletronica": "7s2",
            "cor": [0, 125, 0],
            "grupo": "Metais Alcalinos Terrosos"
        },
        "Lr": {
            "nome": "Laurêncio",
            "sigla": "Lr",
            "nox": [3],
            "eletrons": [2, 8, 18, 32, 32, 10, 2],
            "numeroAtomico": 104,
            "eletronegatividade": 1.2,
            "configuracaoEletronica": "5f14 6d1 7s2",
            "cor": [199, 0, 102],
            "grupo": "Metais de Transição"
        },
        "Rf": {
            "nome": "Rutherfórdio",
            "sigla": "Rf",
            "nox": [4],
            "eletrons": [2, 8, 18, 32, 32, 10, 2],
            "numeroAtomico": 104,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d2 7s2",
            "cor": [204, 0, 89],
            "grupo": "Metais de Transição"
        },
        "Db": {
            "nome": "Dúbnio",
            "sigla": "Db",
            "nox": [5],
            "eletrons": [2, 8, 18, 32, 32, 11, 2],
            "numeroAtomico": 105,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d3 7s2",
            "cor": [209, 0, 79],
            "grupo": "Metais de Transição"
        },
        "Sg": {
            "nome": "Seabórgio",
            "sigla": "Sg",
            "nox": [6],
            "eletrons": [2, 8, 18, 32, 32, 12, 2],
            "numeroAtomico": 106,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d4 7s2",
            "cor": [217, 0, 69],
            "grupo": "Metais de Transição"
        },
        "Bh": {
            "nome": "Bóhrio",
            "sigla": "Bh",
            "nox": [7, 1],
            "eletrons": [2, 8, 18, 32, 32, 13, 2],
            "numeroAtomico": 107,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d5 7s2",
            "cor": [224, 0, 56],
            "grupo": "Metais de Transição"

        },
        "Hs": {
            "nome": "Hássio",
            "sigla": "Hs",
            "nox": [4],
            "eletrons": [2, 8, 18, 32, 32, 14, 2],
            "numeroAtomico": 108,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d6 7s2",
            "cor": [230, 0, 46],
            "grupo": "Metais de Transição"
        },
        "Mt": {
            "nome": "Meitnério",
            "sigla": "Mt",
            "nox": [4],
            "eletrons": [2, 8, 18, 32, 32, 15, 2],
            "numeroAtomico": 109,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "5f14 6d7 7s2",
            "cor": [235, 0, 38],
            "grupo": "Metais de Transição"
        },
        "Ds": {
            "nome": "Darmstácio",
            "sigla": "Ds",
            "nox": [4],
            "eletrons": [2, 8, 18, 32, 32, 16, 2],
            "numeroAtomico": 110,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d8",
            "cor": [235, 0, 38],
            "grupo": "Metais de Transição"
        },
        "Rg": {
            "nome": "Roetgênio",
            "sigla": "Rg",
            "nox": [3],
            "eletrons": [2, 8, 18, 32, 32, 17, 2],
            "numeroAtomico": 111,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d9",
            "cor": [235, 0, 38],
            "grupo": "Metais de Transição"
        },
        "Cn": {
            "nome": "Copernício",
            "sigla": "Cn",
            "nox": [2],
            "eletrons": [2, 8, 18, 32, 32, 18, 2],
            "numeroAtomico": 112,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10",
            "cor": [235, 0, 38],
            "grupo": "Metais de Transição"
        },
        "Uut": {
            "nome": "Unúntrio",
            "sigla": "Uut",
            "nox": [1],
            "eletrons": [2, 8, 18, 32, 32, 18, 3],
            "numeroAtomico": 113,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p1",
            "cor": [235, 0, 38],
            "grupo": "Outros Metais"
        },
        "Fl": {
            "nome": "Fleróvio",
            "sigla": "Fl",
            "nox": [1, 2, 6, 4],
            "eletrons": [2, 8, 18, 32, 32, 18, 4],
            "numeroAtomico": 114,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p2",
            "cor": [235, 0, 38],
            "grupo": "Outros Metais"
        },
        "Uup": {
            "nome": "Ununpêntio",
            "sigla": "Uup",
            "nox": [1],
            "eletrons": [2, 8, 18, 32, 32, 18, 5],
            "numeroAtomico": 115,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p3",
            "cor": [235, 0, 38],
            "grupo": "Outros Metais"
        },
        "Lv": {
            "nome": "Livermório",
            "sigla": "Lv",
            "nox": [1, 2, 4],
            "eletrons": [2, 8, 18, 32, 32, 18, 6],
            "numeroAtomico": 116,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p4",
            "cor": [235, 0, 38],
            "grupo": "Outros Metais"
        },
        "Uus": {
            "nome": "Ununséptio",
            "sigla": "Uus",
            "nox": [-1, 1, 3, 5, 7],
            "eletrons": [2, 8, 18, 32, 32, 18, 7],
            "numeroAtomico": 117,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p5",
            "cor": [235, 0, 38],
            "grupo": "Não Metais"
        },
        "Uuo": {
            "nome": "Ununóctio",
            "sigla": "Uuo",
            "nox": [0],
            "eletrons": [2, 8, 18, 32, 32, 18, 8],
            "numeroAtomico": 118,
            "eletronegatividade": 0.0,
            "configuracaoEletronica": "7s2 5f14 6d10 7p6",
            "cor": [235, 0, 38],
            "grupo": "Gases Nobres"
        },
        "La": {
            "nome": "Lantânio",
            "sigla": "La",
            "nox": [3],
            "eletrons": [2, 8, 18, 18, 9, 2, 0],
            "numeroAtomico": 57,
            "eletronegatividade": 1.10,
            "configuracaoEletronica": "5d1 6s2 4f0",
            "cor": [112, 212, 255],
            "grupo": "Metais de Transição Interna"
        },
        "Ce": {
            "nome": "Cério",
            "sigla": "Ce",
            "nox": [3, 4],
            "eletrons": [2, 8, 18, 19, 9, 2, 0],
            "numeroAtomico": 58,
            "eletronegatividade": 1.11,
            "configuracaoEletronica": "4f1 5d1 6s2",
            "cor": [255, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Pr": {
            "nome": "Praseodímio",
            "sigla": "Pr",
            "nox": [3, 4],
            "eletrons": [2, 8, 18, 21, 8, 2, 0],
            "numeroAtomico": 59,
            "eletronegatividade": 1.12,
            "configuracaoEletronica": "4f3 6s2",
            "cor": [217, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Nd": {
            "nome": "Neodímio",
            "sigla": "Nd",
            "nox": [3, 2, 4],
            "eletrons": [2, 8, 18, 22, 8, 2, 0],
            "numeroAtomico": 60,
            "eletronegatividade": 1.14,
            "configuracaoEletronica": "4f4 6s2",
            "cor": [199, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Pm": {
            "nome": "Promécio",
            "sigla": "Pm",
            "nox": [3],
            "eletrons": [2, 8, 18, 23, 8, 2, 0],
            "numeroAtomico": 61,
            "eletronegatividade": 1.13,
            "configuracaoEletronica": "4f5 6s2",
            "cor": [163, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Sm": {
            "nome": "Samário",
            "sigla": "Sm",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 24, 8, 2, 0],
            "numeroAtomico": 62,
            "eletronegatividade": 1.17,
            "configuracaoEletronica": "4f6 6s2",
            "cor": [143, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Eu": {
            "nome": "Európio",
            "sigla": "Eu",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 25, 8, 2, 0],
            "numeroAtomico": 63,
            "eletronegatividade": 1.2,
            "configuracaoEletronica": "4f7 6s2",
            "cor": [97, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Gd": {
            "nome": "Gadolínio",
            "sigla": "Gd",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 25, 9, 2, 0],
            "numeroAtomico": 64,
            "eletronegatividade": 1.2,
            "configuracaoEletronica": "4f7 5d1 6s2",
            "cor": [69, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Tb": {
            "nome": "Térbio",
            "sigla": "Tb",
            "nox": [3, 4],
            "eletrons": [2, 8, 18, 27, 8, 2, 0],
            "numeroAtomico": 65,
            "eletronegatividade": 1.09,
            "configuracaoEletronica": "4f9 6s2",
            "cor": [48, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Dy": {
            "nome": "Disprósio",
            "sigla": "Dy",
            "nox": [3, 2, 4],
            "eletrons": [2, 8, 18, 28, 8, 2, 0],
            "numeroAtomico": 66,
            "eletronegatividade": 1.22,
            "configuracaoEletronica": "4f10 6s2",
            "cor": [31, 255, 199],
            "grupo": "Metais de Transição Interna"
        },
        "Ho": {
            "nome": "Hólmio",
            "sigla": "Ho",
            "nox": [3],
            "eletrons": [2, 8, 18, 29, 8, 2, 0],
            "numeroAtomico": 67,
            "eletronegatividade": 1.23,
            "configuracaoEletronica": "4f11 6s2",
            "cor": [0, 255, 156],
            "grupo": "Metais de Transição Interna"
        },
        "Er": {
            "nome": "Érbio",
            "sigla": "Er",
            "nox": [3],
            "eletrons": [2, 8, 18, 30, 8, 2, 0],
            "numeroAtomico": 68,
            "eletronegatividade": 1.24,
            "configuracaoEletronica": "4f12 6s2",
            "cor": [0, 230, 117],
            "grupo": "Metais de Transição Interna"
        },
        "Tm": {
            "nome": "Túlio",
            "sigla": "Tm",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 31, 8, 2, 0],
            "numeroAtomico": 69,
            "eletronegatividade": 1.25,
            "configuracaoEletronica": "4f13 6s2",
            "cor": [0, 212, 82],
            "grupo": "Metais de Transição Interna"
        },
        "Yb": {
            "nome": "Itérbio",
            "sigla": "Yb",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 32, 8, 2, 0],
            "numeroAtomico": 70,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "4f14 6s2",
            "cor": [0, 191, 56],
            "grupo": "Metais de Transição Interna"
        },
        "Ac": {
            "nome": "Actínio",
            "sigla": "Ac",
            "nox": [3],
            "eletrons": [2, 8, 18, 32, 18, 9, 2],
            "numeroAtomico": 89,
            "eletronegatividade": 1.1,
            "configuracaoEletronica": "6d1 7s2",
            "cor": [112, 171, 250],
            "grupo": "Metais de Transição Interna"
        },
        "Th": {
            "nome": "Tório",
            "sigla": "Th",
            "nox": [4, 2, 3],
            "eletrons": [2, 8, 18, 32, 18, 10, 2],
            "numeroAtomico": 90,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "6d2 7s2",
            "cor": [0, 186, 255],
            "grupo": "Metais de Transição Interna"
        },
        "Pa": {
            "nome": "Protactínio",
            "sigla": "Pa",
            "nox": [5, 4, 3],
            "eletrons": [2, 8, 18, 32, 20, 9, 2],
            "numeroAtomico": 91,
            "eletronegatividade": 1.5,
            "configuracaoEletronica": "5f2 6d1 7s2",
            "cor": [0, 161, 255],
            "grupo": "Metais de Transição Interna"
        },
        "U": {
            "nome": "Urânio",
            "sigla": "U",
            "nox": [6, 5, 4, 3],
            "eletrons": [2, 8, 18, 32, 21, 9, 2],
            "numeroAtomico": 92,
            "eletronegatividade": 1.38,
            "configuracaoEletronica": "5f3 6d1 7s2",
            "cor": [0, 143, 255],
            "grupo": "Metais de Transição Interna"
        },
        "Np": {
            "nome": "Neptúnio",
            "sigla": "Np",
            "nox": [5, 3, 4, 2, 6, 7],
            "eletrons": [2, 8, 18, 32, 22, 9, 2],
            "numeroAtomico": 93,
            "eletronegatividade": 1.36,
            "configuracaoEletronica": "5f4 6d1 7s2",
            "cor": [0, 128, 255],
            "grupo": "Metais de Transição Interna"
        },
        "Pu": {
            "nome": "Plutônio",
            "sigla": "Pu",
            "nox": [4, 3, 5, 2, 6, 7],
            "eletrons": [2, 8, 18, 32, 24, 8, 2],
            "numeroAtomico": 94,
            "eletronegatividade": 1.28,
            "configuracaoEletronica": "5f6 7s2",
            "cor": [0, 107, 255],
            "grupo": "Metais de Transição Interna"
        },
        "Am": {
            "nome": "Amerício",
            "sigla": "Am",
            "nox": [3, 2, 4, 5, 6],
            "eletrons": [2, 8, 18, 32, 25, 8, 2],
            "numeroAtomico": 95,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f7 7s2",
            "cor": [84, 92, 242],
            "grupo": "Metais de Transição Interna"
        },
        "Cm": {
            "nome": "Cúrio",
            "sigla": "Cm",
            "nox": [3, 4, 2],
            "eletrons": [2, 8, 18, 32, 25, 9, 2],
            "numeroAtomico": 96,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f7 6d1 7s2",
            "cor": [120, 92, 227],
            "grupo": "Metais de Transição Interna"
        },
        "Bk": {
            "nome": "Berquélio",
            "sigla": "Bk",
            "nox": [3, 4],
            "eletrons": [2, 8, 18, 32, 27, 8, 2],
            "numeroAtomico": 97,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f9 7s2",
            "cor": [138, 79, 227],
            "grupo": "Metais de Transição Interna"
        },
        "Cf": {
            "nome": "Californium",
            "sigla": "Cf",
            "nox": [3, 2, 4],
            "eletrons": [2, 8, 18, 32, 28, 8, 2],
            "numeroAtomico": 98,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f10 7s2",
            "cor": [161, 54, 212],
            "grupo": "Metais de Transição Interna"
        },
        "Es": {
            "nome": "Einstênio",
            "sigla": "Es",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 32, 29, 8, 2],
            "numeroAtomico": 99,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f11 7s2",
            "cor": [179, 31, 212],
            "grupo": "Metais de Transição Interna"
        },
        "Fm": {
            "nome": "Férmio",
            "sigla": "Fm",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 32, 30, 8, 2],
            "numeroAtomico": 100,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f12 7s2",
            "cor": [179, 31, 186],
            "grupo": "Metais de Transição Interna"
        },
        "Md": {
            "nome": "Mendelévio",
            "sigla": "Md",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 32, 31, 8, 2],
            "numeroAtomico": 101,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f13 7s2",
            "cor": [179, 13, 166],
            "grupo": "Metais de Transição Interna"
        },
        "No": {
            "nome": "Nobélio",
            "sigla": "No",
            "nox": [3, 2],
            "eletrons": [2, 8, 18, 32, 32, 8, 2],
            "numeroAtomico": 102,
            "eletronegatividade": 1.3,
            "configuracaoEletronica": "5f14 7s2",
            "cor": [189, 13, 135],
            "grupo": "Metais de Transição Interna"
        }
    }
};
