package br.com.ahe.sd.trabalho.corba;


/**
* corba/_AcaoDAOStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

public class _AcaoDAOStub extends org.omg.CORBA.portable.ObjectImpl implements AcaoDAO
{

  public br.com.ahe.sd.trabalho.corba.Acao criaAcao (String codigoEmpresa)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criaAcao", true);
                $out.write_string (codigoEmpresa);
                $in = _invoke ($out);
                br.com.ahe.sd.trabalho.corba.Acao $result = AcaoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return criaAcao (codigoEmpresa        );
            } finally {
                _releaseReply ($in);
            }
  } // criaAcao

  public Acao buscaAcap (String codigoEmpresa)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscaAcap", true);
                $out.write_string (codigoEmpresa);
                $in = _invoke ($out);
                br.com.ahe.sd.trabalho.corba.Acao $result = AcaoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscaAcap (codigoEmpresa        );
            } finally {
                _releaseReply ($in);
            }
  } // buscaAcap

  public void criaMovimentacaoAcao (br.com.ahe.sd.trabalho.corba.Acao acao, String tipo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criaMovimentacaoAcao", true);
                AcaoHelper.write ($out, acao);
                $out.write_string (tipo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                criaMovimentacaoAcao (acao, tipo        );
            } finally {
                _releaseReply ($in);
            }
  } // criaMovimentacaoAcao

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/AcaoDAO:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AcaoDAOStub
