package br.com.ahe.sd.trabalho.corba;


/**
* corba/_CarteiraDAOStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public class _CarteiraDAOStub extends org.omg.CORBA.portable.ObjectImpl implements CarteiraDAO
{

  public Carteira criaCarteira (String nomeUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criaCarteira", true);
                $out.write_string (nomeUsuario);
                $in = _invoke ($out);
                Carteira $result = CarteiraHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return criaCarteira (nomeUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // criaCarteira

  public Carteira buscaCarteira (String nomeUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscaCarteira", true);
                $out.write_string (nomeUsuario);
                $in = _invoke ($out);
                Carteira $result = CarteiraHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscaCarteira (nomeUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // buscaCarteira

  public void criaMovimentacaoCarteira (Acao acao, Carteira carteira, double valor, double qtd, String tipo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criaMovimentacaoCarteira", true);
                AcaoHelper.write ($out, acao);
                CarteiraHelper.write ($out, carteira);
                $out.write_double (valor);
                $out.write_double (qtd);
                $out.write_string (tipo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                criaMovimentacaoCarteira (acao, carteira, valor, qtd, tipo        );
            } finally {
                _releaseReply ($in);
            }
  } // criaMovimentacaoCarteira

  public boolean isAcaoComprada (Acao acao, Carteira carteira, int qtd)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("isAcaoComprada", true);
                AcaoHelper.write ($out, acao);
                CarteiraHelper.write ($out, carteira);
                $out.write_long (qtd);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return isAcaoComprada (acao, carteira, qtd        );
            } finally {
                _releaseReply ($in);
            }
  } // isAcaoComprada

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/CarteiraDAO:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CarteiraDAOStub
