package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/_UsuarioDAOStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public class _UsuarioDAOStub extends org.omg.CORBA.portable.ObjectImpl implements br.com.ahe.sd.trabalho.corba.UsuarioDAO
{

  public br.com.ahe.sd.trabalho.corba.Usuario validaUsuario (String nomeUsuario, String senhaUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validaUsuario", true);
                $out.write_string (nomeUsuario);
                $out.write_string (senhaUsuario);
                $in = _invoke ($out);
                br.com.ahe.sd.trabalho.corba.Usuario $result = br.com.ahe.sd.trabalho.corba.UsuarioHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validaUsuario (nomeUsuario, senhaUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // validaUsuario

  public double buscaSaldoDisponivel (String nomeUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscaSaldoDisponivel", true);
                $out.write_string (nomeUsuario);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscaSaldoDisponivel (nomeUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // buscaSaldoDisponivel

  public double buscaSaldoGeral (String nomeUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscaSaldoGeral", true);
                $out.write_string (nomeUsuario);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscaSaldoGeral (nomeUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // buscaSaldoGeral

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br.com.ahe.sd.trabalho.corba/UsuarioDAO:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _UsuarioDAOStub
