package br.com.ahe.sd.trabalho.corba;


/**
* corba/AcaoDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

public interface AcaoDAO extends AcaoDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AcaoDAO
