package br.com.ahe.sd.trabalho.corba;


/**
* corba/AcaoDAOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

@SuppressWarnings( "cast" )
abstract public class AcaoDAOHelper
{
  private static String  _id = "IDL:corba/AcaoDAO:1.0";

  public static void insert (org.omg.CORBA.Any a, AcaoDAO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AcaoDAO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.ahe.sd.trabalho.corba.AcaoDAOHelper.id (), "AcaoDAO");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AcaoDAO read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AcaoDAOStub.class));
  }

public static void write (org.omg.CORBA.portable.OutputStream ostream, AcaoDAO value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AcaoDAO narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AcaoDAO)
      return (AcaoDAO)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AcaoDAOStub stub = new _AcaoDAOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AcaoDAO unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AcaoDAO)
      return (AcaoDAO)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AcaoDAOStub stub = new _AcaoDAOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
