package br.com.ahe.sd.trabalho.corba;

/**
* corba/AcaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public final class AcaoHolder implements org.omg.CORBA.portable.Streamable
{
  public Acao value = null;

  public AcaoHolder ()
  {
  }

  public AcaoHolder (Acao initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = AcaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AcaoHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AcaoHelper.type ();
  }

}
