package br.com.ahe.sd.trabalho.corba;


/**
* corba/AcaoDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

public abstract class AcaoDAOPOA extends org.omg.PortableServer.Servant
 implements AcaoDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer> ();
  static
  {
    _methods.put ("criaAcao", new java.lang.Integer (0));
    _methods.put ("buscaAcap", new java.lang.Integer (1));
    _methods.put ("criaMovimentacaoAcao", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = _methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/AcaoDAO/criaAcao
       {
         String codigoEmpresa = in.read_string ();
         br.com.ahe.sd.trabalho.corba.Acao $result = null;
         $result = this.criaAcao (codigoEmpresa);
         out = $rh.createReply();
         AcaoHelper.write (out, $result);
         break;
       }

       case 1:  // corba/AcaoDAO/buscaAcap
       {
         String codigoEmpresa = in.read_string ();
         br.com.ahe.sd.trabalho.corba.Acao $result = null;
         $result = this.buscaAcap (codigoEmpresa);
         out = $rh.createReply();
         AcaoHelper.write (out, $result);
         break;
       }

       case 2:  // corba/AcaoDAO/criaMovimentacaoAcao
       {
         br.com.ahe.sd.trabalho.corba.Acao acao = AcaoHelper.read (in);
         String tipo = in.read_string ();
         this.criaMovimentacaoAcao (acao, tipo);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/AcaoDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AcaoDAO _this() 
  {
    return AcaoDAOHelper.narrow(
    super._this_object());
  }

  public AcaoDAO _this(org.omg.CORBA.ORB orb) 
  {
    return AcaoDAOHelper.narrow(
    super._this_object(orb));
  }


} // class AcaoDAOPOA
