package br.com.ahe.sd.trabalho.corba;

/**
* corba/AcaoDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

public final class AcaoDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public AcaoDAO value = null;

  public AcaoDAOHolder ()
  {
  }

  public AcaoDAOHolder (AcaoDAO initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = AcaoDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AcaoDAOHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AcaoDAOHelper.type ();
  }

}
