package br.com.ahe.sd.trabalho.corba;


/**
 * corba/Acao.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from carteiradao.idl
 * Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
 */

public final class Acao implements org.omg.CORBA.portable.IDLEntity
{
	
	private static final long serialVersionUID = 1L;
	public int idAcao = (int)0;
	public int qtdNegocios = (int)0;
	public int codigoEmpresa = (int)0;
	
	public Acao ()
	{
	} // ctor
	
	public Acao (int _idAcao, int _qtdNegocios, int _codigoEmpresa)
	{
		this.idAcao = _idAcao;
		this.qtdNegocios = _qtdNegocios;
		this.codigoEmpresa = _codigoEmpresa;
	} // ctor
	
} // class Acao
