package br.com.ahe.sd.trabalho.corba;


/**
* corba/AcaoDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from acaodao.idl
* Quarta-feira, 6 de Agosto de 2014 20h17min55s BRT
*/

public interface AcaoDAOOperations 
{
  Acao criaAcao (String codigoEmpresa);
  Acao buscaAcap (String codigoEmpresa);
  void criaMovimentacaoAcao (Acao acao, String tipo);
} // interface AcaoDAOOperations
