package br.com.ahe.sd.trabalho.corba;


/**
* corba/CarteiraDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public abstract class CarteiraDAOPOA extends org.omg.PortableServer.Servant
 implements CarteiraDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer> ();
  static
  {
    _methods.put ("criaCarteira", new java.lang.Integer (0));
    _methods.put ("buscaCarteira", new java.lang.Integer (1));
    _methods.put ("criaMovimentacaoCarteira", new java.lang.Integer (2));
    _methods.put ("isAcaoComprada", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = _methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/CarteiraDAO/criaCarteira
       {
         String nomeUsuario = in.read_string ();
         br.com.ahe.sd.trabalho.corba.Carteira $result = null;
         $result = this.criaCarteira (nomeUsuario);
         out = $rh.createReply();
         CarteiraHelper.write (out, $result);
         break;
       }

       case 1:  // corba/CarteiraDAO/buscaCarteira
       {
         String nomeUsuario = in.read_string ();
         br.com.ahe.sd.trabalho.corba.Carteira $result = null;
         $result = this.buscaCarteira (nomeUsuario);
         out = $rh.createReply();
         CarteiraHelper.write (out, $result);
         break;
       }

       case 2:  // corba/CarteiraDAO/criaMovimentacaoCarteira
       {
         Acao acao = AcaoHelper.read (in);
         br.com.ahe.sd.trabalho.corba.Carteira carteira = CarteiraHelper.read (in);
         double valor = in.read_double ();
         double qtd = in.read_double ();
         String tipo = in.read_string ();
         this.criaMovimentacaoCarteira (acao, carteira, valor, qtd, tipo);
         out = $rh.createReply();
         break;
       }

       case 3:  // corba/CarteiraDAO/isAcaoComprada
       {
         Acao acao = AcaoHelper.read (in);
         br.com.ahe.sd.trabalho.corba.Carteira carteira = CarteiraHelper.read (in);
         int qtd = in.read_long ();
         boolean $result = false;
         $result = this.isAcaoComprada (acao, carteira, qtd);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/CarteiraDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CarteiraDAO _this() 
  {
    return CarteiraDAOHelper.narrow(
    super._this_object());
  }

  public CarteiraDAO _this(org.omg.CORBA.ORB orb) 
  {
    return CarteiraDAOHelper.narrow(
    super._this_object(orb));
  }


} // class CarteiraDAOPOA
