package br.com.ahe.sd.trabalho.corba;

/**
* corba/CarteiraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public final class CarteiraHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ahe.sd.trabalho.corba.Carteira value = null;

  public CarteiraHolder ()
  {
  }

  public CarteiraHolder (br.com.ahe.sd.trabalho.corba.Carteira initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = CarteiraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarteiraHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarteiraHelper.type ();
  }

}
