package br.com.ahe.sd.trabalho.corba;

/**
* corba/CarteiraDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public final class CarteiraDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public CarteiraDAO value = null;

  public CarteiraDAOHolder ()
  {
  }

  public CarteiraDAOHolder (CarteiraDAO initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = CarteiraDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarteiraDAOHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarteiraDAOHelper.type ();
  }

}
