package br.com.ahe.sd.trabalho.corba;


/**
* corba/CarteiraDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public interface CarteiraDAO extends CarteiraDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CarteiraDAO
