package br.com.ahe.sd.trabalho.corba;


/**
* corba/Carteira.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from carteiradao.idl
* Quarta-feira, 6 de Agosto de 2014 20h43min48s BRT
*/

public final class Carteira implements org.omg.CORBA.portable.IDLEntity
{
 
    private static final long serialVersionUID = 1L;
public int idAcao = (int)0;
  public double valorReal = (double)0;

  public Carteira ()
  {
  } // ctor

  public Carteira (int _idAcao, double _valorReal)
  {
    this.idAcao = _idAcao;
    this.valorReal = _valorReal;
  } // ctor

} // class Carteira
