package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/Empresa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from empresadao.idl
* Sábado, 28 de Junho de 2014 21h04min40s BRT
*/

public final class Empresa implements org.omg.CORBA.portable.IDLEntity
{
  
    private static final long serialVersionUID = 1L;
public String nome = null;
  public String sigla = null;

  public Empresa ()
  {
  } // ctor

  public Empresa (String _nome, String _sigla)
  {
    this.nome = _nome;
    this.sigla = _sigla;
  } // ctor

} // class Empresa
