package br.com.ahe.sd.trabalho.corba;

/**
* br.com.ahe.sd.trabalho.corba/EmpresaDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from empresadao.idl
* Sábado, 28 de Junho de 2014 21h04min40s BRT
*/

public final class EmpresaDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ahe.sd.trabalho.corba.EmpresaDAO value = null;

  public EmpresaDAOHolder ()
  {
  }

  public EmpresaDAOHolder (br.com.ahe.sd.trabalho.corba.EmpresaDAO initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = br.com.ahe.sd.trabalho.corba.EmpresaDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ahe.sd.trabalho.corba.EmpresaDAOHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ahe.sd.trabalho.corba.EmpresaDAOHelper.type ();
  }

}
