package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/EmpresaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from empresadao.idl
* Sábado, 28 de Junho de 2014 21h04min40s BRT
*/

abstract public class EmpresaHelper
{
  private static String  _id = "IDL:br.com.ahe.sd.trabalho.corba/Empresa:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.ahe.sd.trabalho.corba.Empresa that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.ahe.sd.trabalho.corba.Empresa extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nome",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sigla",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (br.com.ahe.sd.trabalho.corba.EmpresaHelper.id (), "Empresa", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.ahe.sd.trabalho.corba.Empresa read (org.omg.CORBA.portable.InputStream istream)
  {
    br.com.ahe.sd.trabalho.corba.Empresa value = new br.com.ahe.sd.trabalho.corba.Empresa ();
    value.nome = istream.read_string ();
    value.sigla = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.ahe.sd.trabalho.corba.Empresa value)
  {
    ostream.write_string (value.nome);
    ostream.write_string (value.sigla);
  }

}
