package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/EmpresaDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from empresadao.idl
* Sábado, 28 de Junho de 2014 21h04min40s BRT
*/

public interface EmpresaDAOOperations 
{
  void cadastraEmpresa (br.com.ahe.sd.trabalho.corba.Empresa emp);
  boolean isEmpresaCadastrada (br.com.ahe.sd.trabalho.corba.Empresa emp);
} // interface EmpresaDAOOperations
