package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/IFuncoesCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public interface IFuncoesCorbaOperations 
{
  String formataValores (double textoValor);
} // interface IFuncoesCorbaOperations
