package br.com.ahe.sd.trabalho.corba;

/**
* br.com.ahe.sd.trabalho.corba/IFuncoesCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public final class IFuncoesCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ahe.sd.trabalho.corba.IFuncoesCorba value = null;

  public IFuncoesCorbaHolder ()
  {
  }

  public IFuncoesCorbaHolder (br.com.ahe.sd.trabalho.corba.IFuncoesCorba initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = br.com.ahe.sd.trabalho.corba.IFuncoesCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ahe.sd.trabalho.corba.IFuncoesCorbaHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ahe.sd.trabalho.corba.IFuncoesCorbaHelper.type ();
  }

}
