package br.com.ahe.sd.trabalho.corba;

/**
* br.com.ahe.sd.trabalho.corba/UsuarioDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public final class UsuarioDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ahe.sd.trabalho.corba.UsuarioDAO value = null;

  public UsuarioDAOHolder ()
  {
  }

  public UsuarioDAOHolder (br.com.ahe.sd.trabalho.corba.UsuarioDAO initialValue)
  {
    this.value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    this.value = br.com.ahe.sd.trabalho.corba.UsuarioDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ahe.sd.trabalho.corba.UsuarioDAOHelper.write (o, this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ahe.sd.trabalho.corba.UsuarioDAOHelper.type ();
  }

}
