package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/UsuarioDAOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

abstract public class UsuarioDAOHelper
{
  private static String  _id = "IDL:br.com.ahe.sd.trabalho.corba/UsuarioDAO:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.ahe.sd.trabalho.corba.UsuarioDAO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.ahe.sd.trabalho.corba.UsuarioDAO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.ahe.sd.trabalho.corba.UsuarioDAOHelper.id (), "UsuarioDAO");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.ahe.sd.trabalho.corba.UsuarioDAO read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UsuarioDAOStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.ahe.sd.trabalho.corba.UsuarioDAO value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.ahe.sd.trabalho.corba.UsuarioDAO narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ahe.sd.trabalho.corba.UsuarioDAO)
      return (br.com.ahe.sd.trabalho.corba.UsuarioDAO)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ahe.sd.trabalho.corba._UsuarioDAOStub stub = new br.com.ahe.sd.trabalho.corba._UsuarioDAOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.ahe.sd.trabalho.corba.UsuarioDAO unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ahe.sd.trabalho.corba.UsuarioDAO)
      return (br.com.ahe.sd.trabalho.corba.UsuarioDAO)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ahe.sd.trabalho.corba._UsuarioDAOStub stub = new br.com.ahe.sd.trabalho.corba._UsuarioDAOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
