package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/UsuarioDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public interface UsuarioDAOOperations 
{
  br.com.ahe.sd.trabalho.corba.Usuario validaUsuario (String nomeUsuario, String senhaUsuario);
  double buscaSaldoDisponivel (String nomeUsuario);
  double buscaSaldoGeral (String nomeUsuario);
} // interface UsuarioDAOOperations
