package br.com.ahe.sd.trabalho.corba;


/**
* br.com.ahe.sd.trabalho.corba/UsuarioDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from funcorescorba.idl
* Sábado, 28 de Junho de 2014 20h27min04s BRT
*/

public abstract class UsuarioDAOPOA extends org.omg.PortableServer.Servant
 implements br.com.ahe.sd.trabalho.corba.UsuarioDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer> ();
  static
  {
    _methods.put ("validaUsuario", new java.lang.Integer (0));
    _methods.put ("buscaSaldoDisponivel", new java.lang.Integer (1));
    _methods.put ("buscaSaldoGeral", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br.com.ahe.sd.trabalho.corba/UsuarioDAO/validaUsuario
       {
         String nomeUsuario = in.read_string ();
         String senhaUsuario = in.read_string ();
         br.com.ahe.sd.trabalho.corba.Usuario $result = null;
         $result = this.validaUsuario (nomeUsuario, senhaUsuario);
         out = $rh.createReply();
         br.com.ahe.sd.trabalho.corba.UsuarioHelper.write (out, $result);
         break;
       }

       case 1:  // br.com.ahe.sd.trabalho.corba/UsuarioDAO/buscaSaldoDisponivel
       {
         String nomeUsuario = in.read_string ();
         double $result = (double)0;
         $result = this.buscaSaldoDisponivel (nomeUsuario);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // br.com.ahe.sd.trabalho.corba/UsuarioDAO/buscaSaldoGeral
       {
         String nomeUsuario = in.read_string ();
         double $result = (double)0;
         $result = this.buscaSaldoGeral (nomeUsuario);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br.com.ahe.sd.trabalho.corba/UsuarioDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public UsuarioDAO _this() 
  {
    return UsuarioDAOHelper.narrow(
    super._this_object());
  }

  public UsuarioDAO _this(org.omg.CORBA.ORB orb) 
  {
    return UsuarioDAOHelper.narrow(
    super._this_object(orb));
  }


} // class UsuarioDAOPOA
