/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgendaGUI.java
 *
 * Created on 20/10/2010, 15:41:31
 */
package br.com.ahe.poo.um.provas.p4;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;

public class AgendaGUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form AgendaGUI */
    public AgendaGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jLabel1 = new javax.swing.JLabel();
        this.textFieldData = new javax.swing.JTextField();
        this.jLabel2 = new javax.swing.JLabel();
        this.textFieldEfemeride = new javax.swing.JTextField();
        this.jButton1 = new javax.swing.JButton();
        this.jLabel3 = new javax.swing.JLabel();
        this.textFieldHora = new javax.swing.JTextField();
        this.jLabel4 = new javax.swing.JLabel();
        this.textFieldDescricao = new javax.swing.JTextField();
        this.jLabel5 = new javax.swing.JLabel();
        this.textFieldTempo = new javax.swing.JTextField();
        this.jLabel6 = new javax.swing.JLabel();
        this.comboBoxPrioridade = new javax.swing.JComboBox();
        this.jButton2 = new javax.swing.JButton();
        this.jButton3 = new javax.swing.JButton();
        this.jButton4 = new javax.swing.JButton();
        this.textFieldTempoMedio = new javax.swing.JTextField();
        this.textFieldDiaConsulta = new javax.swing.JTextField();
        this.jLabel7 = new javax.swing.JLabel();
        this.jLabel8 = new javax.swing.JLabel();
        this.comboBoxPrioridadeConsulta = new javax.swing.JComboBox();
        this.jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.jLabel1.setText("Data do compromisso:");

        this.textFieldData.setName("textFieldData"); // NOI18N

        this.jLabel2.setText("Efeméride:");

        this.textFieldEfemeride.setName("textFieldEfemeride"); // NOI18N

        this.jButton1.setText("Adicionar compromisso");
        this.jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        this.jLabel3.setText("Hora do compromisso:");

        this.textFieldHora.setName("textFieldHora"); // NOI18N

        this.jLabel4.setText("Descrição:");

        this.textFieldDescricao.setName("textFieldDescricao"); // NOI18N

        this.jLabel5.setText("Tempo:");

        this.textFieldTempo.setName("textFieldDescricao"); // NOI18N

        this.jLabel6.setText("Prioridade:");

        this.comboBoxPrioridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baixa", "Normal", "Alta" }));

        this.jButton2.setText("Adicionar data");
        this.jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        this.jButton3.setText("Dados do menor compromisso");
        this.jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        this.jButton4.setText("Mostrar tempo médio do dia");
        this.jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        this.jLabel7.setText("Informe o dia:");

        this.jLabel8.setText("Informe o dia e a prioridade:");

        this.comboBoxPrioridadeConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baixa", "Normal", "Alta" }));

        this.jButton5.setText("Mostrar compromissos");
        this.jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(this.jButton2)
                            .addComponent(this.jButton1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(this.jLabel4)
                                    .addComponent(this.jLabel5)
                                    .addComponent(this.jLabel6))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(this.textFieldDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(this.textFieldTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(this.comboBoxPrioridade, 0, 317, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(this.jLabel3)
                                    .addComponent(this.jLabel1)
                                    .addComponent(this.jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(this.textFieldData, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(this.textFieldHora, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(this.textFieldEfemeride, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.textFieldTempoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.textFieldDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.comboBoxPrioridadeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.jButton5)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel1)
                    .addComponent(this.textFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel2)
                    .addComponent(this.textFieldEfemeride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(this.jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel3)
                    .addComponent(this.textFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel4)
                    .addComponent(this.textFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel5)
                    .addComponent(this.textFieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.comboBoxPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(this.jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel7)
                    .addComponent(this.textFieldTempoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jLabel8)
                    .addComponent(this.comboBoxPrioridadeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.textFieldDiaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.jButton5))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Map<Date, DataAgenda> agenda = new HashMap<Date, DataAgenda>();
    private DataAgenda dataAgendaAtual = null;

    private boolean isVazio(String s) {
        return s == null || s.isEmpty();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if (this.dataAgendaAtual != null) {
                if (isVazio(this.textFieldHora.getText())) {
                    JOptionPane.showMessageDialog(null, "Informe a hora!");
                    return;
                }

                if (isVazio(this.textFieldDescricao.getText())) {
                    JOptionPane.showMessageDialog(null, "Informe a descrição!");
                    return;
                }

                if (isVazio(this.textFieldTempo.getText())) {
                    JOptionPane.showMessageDialog(null, "Informe o tempo!");
                    return;
                }

                Compromisso compromisso = new Compromisso();
                compromisso.setDescricao(this.textFieldDescricao.getText());
                compromisso.setHora(this.textFieldHora.getText());
                compromisso.setTempo(Integer.valueOf(this.textFieldTempo.getText()));
                compromisso.setPrioridade(((String) this.comboBoxPrioridade.getSelectedItem()).charAt(0));

                this.dataAgendaAtual.addCompromisso(compromisso);
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma data de agenda informada!");
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Informe um tempo válido (Inteiro)!");
        }catch(ArrayStoreException ase){
            JOptionPane.showMessageDialog(null, "Já existe um compromisso para esta hora!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (isVazio(this.textFieldData.getText())) {
                JOptionPane.showMessageDialog(null, "Informe a data!");
                return;
            }

            DateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
            Date data = dateFormat.parse(this.textFieldData.getText());

            DataAgenda dataTeste = this.agenda.get(data);
            if (dataTeste != null) {
                this.dataAgendaAtual = dataTeste;
                JOptionPane.showMessageDialog(null, dataTeste.getCompromissosPrioridade('A'));
            } else {
                String efemeride = this.textFieldEfemeride.getText();

                DataAgenda dataAgenda = new DataAgenda();
                dataAgenda.setData(data);
                dataAgenda.setEfemeride(efemeride);

                this.agenda.put(data, dataAgenda);
                this.dataAgendaAtual = dataAgenda;
            }

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "A data da agenda é inválida!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Compromisso menor = new Compromisso();
        menor.setTempo(Integer.MAX_VALUE);

        for(DataAgenda dataAgenda : this.agenda.values()){
            for(Compromisso compromisso : dataAgenda.getCompromissos().values()){
                if(compromisso.getTempo() < menor.getTempo()){
                    menor = compromisso;
                }
            }
        }

       JOptionPane.showMessageDialog(null, menor);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
            DateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
            Date data = dateFormat.parse(this.textFieldTempoMedio.getText());

            DataAgenda dataTeste = this.agenda.get(data);
            if (dataTeste != null) {
                JOptionPane.showMessageDialog(null, dataTeste.getTempoMedio());
            } else {
                JOptionPane.showMessageDialog(null, "Esta data não foi cadastrada!");
            }

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "A data é inválida!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
            DateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
            Date data = dateFormat.parse(this.textFieldDiaConsulta.getText());

            DataAgenda dataTeste = this.agenda.get(data);
            if (dataTeste != null) {
                char prioridade = ((String) this.comboBoxPrioridadeConsulta.getSelectedItem()).charAt(0);
                JOptionPane.showMessageDialog(null, dataTeste.getDadosCompromissosPrioridade(prioridade));
            } else {
                JOptionPane.showMessageDialog(null, "Esta data não foi cadastrada!");
            }

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "A data é inválida!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AgendaGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox comboBoxPrioridade;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox comboBoxPrioridadeConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textFieldData;
    private javax.swing.JTextField textFieldDescricao;
    private javax.swing.JTextField textFieldDiaConsulta;
    private javax.swing.JTextField textFieldEfemeride;
    private javax.swing.JTextField textFieldHora;
    private javax.swing.JTextField textFieldTempo;
    private javax.swing.JTextField textFieldTempoMedio;
    // End of variables declaration//GEN-END:variables
}
