package br.com.ahe.sd.corba.boasvindas.stub;


/**
 * stub/MsgBoasVindasPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/boasvindas/idl/BoasVindas.idl
 * Quarta-feira, 4 de Junho de 2014 18h53min34s BRT
 */

@SuppressWarnings({"all"})
public abstract class MsgBoasVindasPOA extends org.omg.PortableServer.Servant implements MsgBoasVindasOperations, org.omg.CORBA.portable.InvokeHandler
{

	// Constructors

	@SuppressWarnings("rawtypes")
	private static java.util.Hashtable _methods = new java.util.Hashtable ();
	
	static
	{
		_methods.put ("boasVindas", new java.lang.Integer (0));
	}

	public org.omg.CORBA.portable.OutputStream _invoke (String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh)
	{
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue ())
		{
		case 0:  // stub/MsgBoasVindas/boasVindas
		{
			String $result = null;
			$result = this.boasVindas ();
			out = $rh.createReply();
			out.write_string ($result);
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = {
	"IDL:stub/MsgBoasVindas:1.0"};

	public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
	{
		return (String[])__ids.clone ();
	}

	public MsgBoasVindas _this() 
	{
		return MsgBoasVindasHelper.narrow(
				super._this_object());
	}

	public MsgBoasVindas _this(org.omg.CORBA.ORB orb) 
	{
		return MsgBoasVindasHelper.narrow(
				super._this_object(orb));
	}


} // class MsgBoasVindasPOA
