package br.com.ahe.sd.corba.boasvindas.stub;

/**
* stub/MsgBoasVindasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/boasvindas/idl/BoasVindas.idl
* Quarta-feira, 4 de Junho de 2014 18h53min34s BRT
*/
@SuppressWarnings({"all"})
public final class MsgBoasVindasHolder implements org.omg.CORBA.portable.Streamable
{
  public MsgBoasVindas value = null;

  public MsgBoasVindasHolder ()
  {
  }

  public MsgBoasVindasHolder (MsgBoasVindas initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MsgBoasVindasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MsgBoasVindasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MsgBoasVindasHelper.type ();
  }

}
