package br.com.ahe.sd.corba.boasvindas.stub;


/**
* stub/MsgBoasVindasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/boasvindas/idl/BoasVindas.idl
* Quarta-feira, 4 de Junho de 2014 18h53min34s BRT
*/

public interface MsgBoasVindasOperations 
{
  String boasVindas ();
} // interface MsgBoasVindasOperations
