package br.com.ahe.sd.corba.boasvindas.stub;

import java.io.IOException;
import java.io.ObjectInputStream;

import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.ObjectImpl;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.RemarshalException;

/**
 * stub/_MsgBoasVindasStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/boasvindas/idl/BoasVindas.idl
 * Quarta-feira, 4 de Junho de 2014 18h53min34s BRT
 */

public class MsgBoasVindasStub extends ObjectImpl implements MsgBoasVindas {

	@Override
	public String boasVindas () {
		InputStream $in = null;
		try {
			OutputStream $out = _request ("boasVindas", true);
			$in = _invoke ($out);
			String $result = $in.read_string ();
			return $result;
		} catch (ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (RemarshalException $rm) {
			return boasVindas ( );
		} finally {
			_releaseReply ($in);
		}
	} // boasVindas

	// Type-specific CORBA::Object operations
	private static String[] __ids = {"IDL:stub/MsgBoasVindas:1.0"};

	@Override
	public String[] _ids () {
		return __ids.clone ();
	}

	private void readObject (ObjectInputStream s) throws IOException {
		String str = s.readUTF ();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
		try {
			org.omg.CORBA.Object obj = orb.string_to_object (str);
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
			_set_delegate (delegate);
		} finally {
			orb.destroy() ;
		}
	}

	private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
	{
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
		try {
			String str = orb.object_to_string (this);
			s.writeUTF (str);
		} finally {
			orb.destroy() ;
		}
	}
} // class _MsgBoasVindasStub
