package br.com.ahe.sd.corba.calculadora;


/**
* calculadora/calc_alfa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/calculadora/Calculadora.idl
* Quarta-feira, 4 de Junho de 2014 19h16min05s BRT
*/
@SuppressWarnings({"all"})
public interface calc_alfa extends calc_alfaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc_alfa
