package br.com.ahe.sd.corba.calculadora;

/**
* calculadora/calc_alfaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/calculadora/Calculadora.idl
* Quarta-feira, 4 de Junho de 2014 19h16min05s BRT
*/
@SuppressWarnings({"all"})
public final class calc_alfaHolder implements org.omg.CORBA.portable.Streamable
{
  public calc_alfa value = null;

  public calc_alfaHolder ()
  {
  }

  public calc_alfaHolder (calc_alfa initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc_alfaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc_alfaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc_alfaHelper.type ();
  }

}
