package br.com.ahe.sd.corba.calculadora;


/**
* calculadora/calc_numericaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/calculadora/Calculadora.idl
* Quarta-feira, 4 de Junho de 2014 19h16min05s BRT
*/

public interface calc_numericaOperations 
{
  boolean soma_int (short p1, short p2, org.omg.CORBA.ShortHolder ret);
  boolean sub_int (short p1, short p2, org.omg.CORBA.ShortHolder ret);
  boolean div_double (double p1, double p2, org.omg.CORBA.ShortHolder ret);
  boolean mul_double (double p1, double p2, org.omg.CORBA.ShortHolder ret);
} // interface calc_numericaOperations
