package br.com.ahe.sd.corba.calculadora;


/**
* calculadora/calc_alfaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/roa/Documents/Workspaces/git/faculdade/src/main/java/sd/corba/calculadora/Calculadora.idl
* Quarta-feira, 4 de Junho de 2014 19h16min05s BRT
*/

public interface calc_alfaOperations 
{
  String soma_str (String str1, String str2);
  String mistura_str (String str1, String str2);
} // interface calc_alfaOperations
